[package]
name    = "minimal"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"

[dependencies]
cortex-m    = "0.6.1"
cortex-m-rt = "0.6.10"
lpc8xx-hal  = { version = "0.6.1", features = ["845-rt"] }
panic-halt  = "0.2.0"
